const dataPrincipalProfileEmail = {
  label: '',
  text: '',
  checked: false,
  principal: true,
  social: true,
  professional: true,
  icon: 'EmailOutlinedIcon',
};
const dataPrincipalProfilePhone = {
  label: '',
  text: '',
  checked: false,
  principal: true,
  social: true,
  professional: true,
  icon: 'LocalPhoneOutlinedIcon',
};
const dataPrincipalEducations = {
  label: '',
  title: '',
  institution: '',
  year: '',
  checked: false,
  principal: true,
  social: false,
  professional: true,
  icon: '',
};
const dataPrincipalCareer = {
  label: '',
  company: '',
  position: '',
  data_init: '',
  data_end: '',
  checked: false,
  principal: true,
  social: false,
  professional: true,
  icon: '',
};
const dataPrincipalUrl = {
  label: '',
  name: '',
  url: '',
  icon: '',
  checked: false,
  principal: true,
  social: false,
  professional: true,
};
export const profile = {
  name: {
    label: '',
    text: '',
    checked: false,
    social: true,
    professional: true,
    icon: 'PersonOutlinedIcon',
  },
  last_name: {
    label: '',
    text: '',
    checked: false,
    social: true,
    professional: true,
    icon: 'PersonOutlinedIcon',
  },
  profession: {
    label: '',
    text: '',
    checked: false,
    social: true,
    professional: true,
    icon: 'FilePresentOutlinedIcon',
  },
  occupation: {
    label: '',
    text: '',
    checked: false,
    social: true,
    professional: true,
    icon: 'WorkOutlineOutlinedIcon',
  },
  address: {
    label: '',
    text: '',
    checked: false,
    social: true,
    professional: true,
    icon: 'ExploreOutlinedIcon',
  },
  company: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'WorkOutlineOutlinedIcon',
  },
  position: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'AttachFileOutlinedIcon',
  },
  professional_profile: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'PersonOutlinedIcon',
  },
  phones: [dataPrincipalProfilePhone],
  emails: [dataPrincipalProfileEmail],
  education: [dataPrincipalEducations],
  professional_career: [dataPrincipalCareer],
  urls: [dataPrincipalUrl],
  other_competencies: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'AccessibilityOutlinedIcon',
  },
  skills: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'PersonOutlinedIcon',
  },
  languages: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'TranslateIcon',
  },
  achievements_recognitions: {
    label: '',
    text: '',
    checked: false,
    social: false,
    professional: true,
    icon: 'AccessibilityOutlinedIcon',
  },
};
